

def Evolucion():

  Evolucion = [
    # ── RANGO 1: NOVATO (1–9) ──────────────────────────────
    {"nivel":  1, "titulo": "Aprendiz I",     "clase": "Novato",        "rango": "🪨 Novato",     "tip": "Tu aventura comienza. Da el primer paso hoy."},
    {"nivel":  2, "titulo": "Aprendiz II",    "clase": "Novato",        "rango": "🪨 Novato",     "tip": "Dos días seguidos son mejor que uno. ¡Sigue!"},
    {"nivel":  3, "titulo": "Aprendiz III",   "clase": "Novato",        "rango": "🪨 Novato",     "tip": "Estás formando las bases. No las abandones."},
    {"nivel":  4, "titulo": "Iniciado I",     "clase": "Novato",        "rango": "🪨 Novato",     "tip": "Ya tienes ritmo. Añade un hábito nuevo."},
    {"nivel":  5, "titulo": "Iniciado II",    "clase": "Novato",        "rango": "🪨 Novato",     "tip": "5 niveles completados. Tu cuerpo empieza a notar cambios."},
    {"nivel":  6, "titulo": "Iniciado III",   "clase": "Novato",        "rango": "🪨 Novato",     "tip": "¡Una semana de constancia marca la diferencia!"},
    {"nivel":  7, "titulo": "Iniciado IV",    "clase": "Novato",        "rango": "🪨 Novato",     "tip": "Confía en el proceso. Los resultados llegan."},
    {"nivel":  8, "titulo": "Pupilo I",       "clase": "Novato",        "rango": "🪨 Novato",     "tip": "Ya no eres principiante. Sube la intensidad."},
    {"nivel":  9, "titulo": "Pupilo II",      "clase": "Novato",        "rango": "🪨 Novato",     "tip": "A un paso del bronce. ¡No pares!"},
    # ── RANGO 2: BRONCE (10–19) ────────────────────────────
    {"nivel": 10, "titulo": "Pupilo III",     "clase": "Explorador",    "rango": "🥉 Bronce",     "tip": "¡Bienvenido al rango Bronce! Empieza a diversificar hábitos."},
    {"nivel": 11, "titulo": "Explorador I",   "clase": "Explorador",    "rango": "🥉 Bronce",     "tip": "Explora nuevas categorías. Equilibra tus stats."},
    {"nivel": 12, "titulo": "Explorador II",  "clase": "Explorador",    "rango": "🥉 Bronce",     "tip": "Tu racha vale oro. Protégela cada día."},
    {"nivel": 13, "titulo": "Explorador III", "clase": "Explorador",    "rango": "🥉 Bronce",     "tip": "Ataca el stat más débil con nuevos hábitos."},
    {"nivel": 14, "titulo": "Rastreador I",   "clase": "Explorador",    "rango": "🥉 Bronce",     "tip": "14 niveles. Tu mente ya aceptó el cambio."},
    {"nivel": 15, "titulo": "Rastreador II",  "clase": "Explorador",    "rango": "🥉 Bronce",     "tip": "Medio mes de hábitos diarios. ¡Eso es real!"},
    {"nivel": 16, "titulo": "Rastreador III", "clase": "Explorador",    "rango": "🥉 Bronce",     "tip": "Crea un hábito desafiante que te incomode un poco."},
    {"nivel": 17, "titulo": "Escudero I",     "clase": "Explorador",    "rango": "🥉 Bronce",     "tip": "Ya eres referente para alguien. Sigue siendo consistente."},
    {"nivel": 18, "titulo": "Escudero II",    "clase": "Explorador",    "rango": "🥉 Bronce",     "tip": "Tu disciplina está por encima del 90% de las personas."},
    {"nivel": 19, "titulo": "Escudero III",   "clase": "Explorador",    "rango": "🥉 Bronce",     "tip": "Un nivel más y subes de rango. ¡Dalo todo!"},
    # ── RANGO 3: PLATA (20–34) ─────────────────────────────
    {"nivel": 20, "titulo": "Guerrero I",     "clase": "Guerrero",      "rango": "🥈 Plata",      "tip": "¡Rango Plata desbloqueado! Eres ya un guerrero real."},
    {"nivel": 21, "titulo": "Guerrero II",    "clase": "Guerrero",      "rango": "🥈 Plata",      "tip": "Intenta completar el 100% de tus hábitos esta semana."},
    {"nivel": 22, "titulo": "Guerrero III",   "clase": "Guerrero",      "rango": "🥈 Plata",      "tip": "La constancia a este nivel ya es tu identidad."},
    {"nivel": 23, "titulo": "Luchador I",     "clase": "Guerrero",      "rango": "🥈 Plata",      "tip": "Añade un hábito de alto impacto: frío, ayuno, sprint."},
    {"nivel": 24, "titulo": "Luchador II",    "clase": "Guerrero",      "rango": "🥈 Plata",      "tip": "24 niveles. Llevas semanas de esfuerzo acumulado. ¡Impresionante!"},
    {"nivel": 25, "titulo": "Luchador III",   "clase": "Guerrero",      "rango": "🥈 Plata",      "tip": "A mitad de camino hacia el oro. Refuerza tu stat más débil."},
    {"nivel": 26, "titulo": "Gladiador I",    "clase": "Guerrero",      "rango": "🥈 Plata",      "tip": "Tu cuerpo y tu mente han cambiado. ¿Lo notas?"},
    {"nivel": 27, "titulo": "Gladiador II",   "clase": "Guerrero",      "rango": "🥈 Plata",      "tip": "Reta a alguien a hacer hábitos contigo. La comunidad impulsa."},
    {"nivel": 28, "titulo": "Gladiador III",  "clase": "Guerrero",      "rango": "🥈 Plata",      "tip": "Cada hábito cumplido es un voto por la persona que quieres ser."},
    {"nivel": 29, "titulo": "Campeón I",      "clase": "Guerrero",      "rango": "🥈 Plata",      "tip": "Pocos llegan aquí. Tú sí pudiste. Sigue."},
    {"nivel": 30, "titulo": "Campeón II",     "clase": "Guerrero",      "rango": "🥈 Plata",      "tip": "30 niveles. Eres el top 5% de personas comprometidas."},
    {"nivel": 31, "titulo": "Campeón III",    "clase": "Guerrero",      "rango": "🥈 Plata",      "tip": "Evalúa qué hábitos ya son automáticos y sube la apuesta."},
    {"nivel": 32, "titulo": "Veterano I",     "clase": "Guerrero",      "rango": "🥈 Plata",      "tip": "Eres un veterano. Tu experiencia habla sola."},
    {"nivel": 33, "titulo": "Veterano II",    "clase": "Guerrero",      "rango": "🥈 Plata",      "tip": "Diseña tu semana perfecta de hábitos y ejecútala."},
    {"nivel": 34, "titulo": "Veterano III",   "clase": "Guerrero",      "rango": "🥈 Plata",      "tip": "Un nivel más y entras al rango Oro. ¡Es tu momento!"},
    # ── RANGO 4: ORO (35–49) ───────────────────────────────
    {"nivel": 35, "titulo": "Élite I",        "clase": "Élite",         "rango": "🥇 Oro",        "tip": "¡Rango Oro! Estás en la élite. Tu nivel es excepcional."},
    {"nivel": 36, "titulo": "Élite II",       "clase": "Élite",         "rango": "🥇 Oro",        "tip": "Comparte tu experiencia. Inspirar a otros también suma XP en la vida."},
    {"nivel": 37, "titulo": "Élite III",      "clase": "Élite",         "rango": "🥇 Oro",        "tip": "Tus hábitos ya definen quién eres. No quien quieres ser."},
    {"nivel": 38, "titulo": "Maestro I",      "clase": "Élite",         "rango": "🥇 Oro",        "tip": "Maestro en formación. Perfecciona la calidad de cada hábito."},
    {"nivel": 39, "titulo": "Maestro II",     "clase": "Élite",         "rango": "🥇 Oro",        "tip": "39 niveles. El 99% de la gente nunca llega aquí. Tú sí."},
    {"nivel": 40, "titulo": "Maestro III",    "clase": "Élite",         "rango": "🥇 Oro",        "tip": "40 niveles de pura consistencia. Eso no se compra."},
    {"nivel": 41, "titulo": "Gran Maestro I", "clase": "Élite",         "rango": "🥇 Oro",        "tip": "Empieza a enseñar. El maestro aprende dos veces."},
    {"nivel": 42, "titulo": "Gran Maestro II","clase": "Élite",         "rango": "🥇 Oro",        "tip": "Suma un hábito que cambie tu carrera o tus finanzas."},
    {"nivel": 43, "titulo": "Gran Maestro III","clase": "Élite",        "rango": "🥇 Oro",        "tip": "Cada día que cumples refuerzas una identidad ganadora."},
    {"nivel": 44, "titulo": "Sensei I",       "clase": "Élite",         "rango": "🥇 Oro",        "tip": "Sensei: guías con el ejemplo. Tu coherencia es tu poder."},
    {"nivel": 45, "titulo": "Sensei II",      "clase": "Élite",         "rango": "🥇 Oro",        "tip": "45 niveles. Eres la prueba de que los sistemas funcionan."},
    {"nivel": 46, "titulo": "Sensei III",     "clase": "Élite",         "rango": "🥇 Oro",        "tip": "Haz una revisión completa: ¿qué hábito necesitas reemplazar?"},
    {"nivel": 47, "titulo": "Sensei IV",      "clase": "Élite",         "rango": "🥇 Oro",        "tip": "Estás construyendo un legado. No lo abandones."},
    {"nivel": 48, "titulo": "Sensei V",       "clase": "Élite",         "rango": "🥇 Oro",        "tip": "A las puertas del Platino. Solo los mejores llegan."},
    {"nivel": 49, "titulo": "Sensei VI",      "clase": "Élite",         "rango": "🥇 Oro",        "tip": "Un último esfuerzo. El nivel 50 te espera."},
    # ── RANGO 5: PLATINO (50–64) ───────────────────────────
    {"nivel": 50, "titulo": "Paladín I",      "clase": "Paladín",       "rango": "💎 Platino",    "tip": "¡NIVEL 50! Rango Platino. Eres absolutamente extraordinario."},
    {"nivel": 51, "titulo": "Paladín II",     "clase": "Paladín",       "rango": "💎 Platino",    "tip": "La mitad del camino al 100. Tu historia ya es inspiradora."},
    {"nivel": 52, "titulo": "Paladín III",    "clase": "Paladín",       "rango": "💎 Platino",    "tip": "Sube un hábito de impacto a su versión más difícil."},
    {"nivel": 53, "titulo": "Guardián I",     "clase": "Paladín",       "rango": "💎 Platino",    "tip": "Guardas tu energía, tu tiempo y tu compromiso. Eso es poder."},
    {"nivel": 54, "titulo": "Guardián II",    "clase": "Paladín",       "rango": "💎 Platino",    "tip": "54 niveles. Tu versión de hace un año no te reconocería."},
    {"nivel": 55, "titulo": "Guardián III",   "clase": "Paladín",       "rango": "💎 Platino",    "tip": "Combina hábitos para crear rutinas mañana + noche perfectas."},
    {"nivel": 56, "titulo": "Cruzado I",      "clase": "Paladín",       "rango": "💎 Platino",    "tip": "Luchás por algo más grande que tú. Define tu propósito."},
    {"nivel": 57, "titulo": "Cruzado II",     "clase": "Paladín",       "rango": "💎 Platino",    "tip": "La disciplina que tienes ahora es la libertad que tendrás mañana."},
    {"nivel": 58, "titulo": "Cruzado III",    "clase": "Paladín",       "rango": "💎 Platino",    "tip": "Evalúa tus 4 stats y diseña hábitos para el más rezagado."},
    {"nivel": 59, "titulo": "Cruzado IV",     "clase": "Paladín",       "rango": "💎 Platino",    "tip": "Cada hábito completado es una promesa cumplida a ti mismo."},
    {"nivel": 60, "titulo": "Templario I",    "clase": "Paladín",       "rango": "💎 Platino",    "tip": "60 niveles. Dos tercios del camino. La élite de la élite."},
    {"nivel": 61, "titulo": "Templario II",   "clase": "Paladín",       "rango": "💎 Platino",    "tip": "Agrega un hábito que impacte directamente tu vida financiera."},
    {"nivel": 62, "titulo": "Templario III",  "clase": "Paladín",       "rango": "💎 Platino",    "tip": "Tu constancia a este punto ya es una habilidad rara."},
    {"nivel": 63, "titulo": "Templario IV",   "clase": "Paladín",       "rango": "💎 Platino",    "tip": "Sigue documentando tu progreso. Tu historia motiva a otros."},
    {"nivel": 64, "titulo": "Templario V",    "clase": "Paladín",       "rango": "💎 Platino",    "tip": "A un paso del Diamante. El nivel 65 cambia todo."},
    # ── RANGO 6: DIAMANTE (65–79) ──────────────────────────
    {"nivel": 65, "titulo": "Arcano I",       "clase": "Arcano",        "rango": "💠 Diamante",   "tip": "¡Diamante! Solo el 0.1% de personas llega a este nivel de hábitos."},
    {"nivel": 66, "titulo": "Arcano II",      "clase": "Arcano",        "rango": "💠 Diamante",   "tip": "Tu bienestar, rendimiento y paz interior están transformados."},
    {"nivel": 67, "titulo": "Arcano III",     "clase": "Arcano",        "rango": "💠 Diamante",   "tip": "Crea un sistema de hábitos para alguien que amas."},
    {"nivel": 68, "titulo": "Hechicero I",    "clase": "Arcano",        "rango": "💠 Diamante",   "tip": "Conviertes intenciones en acciones como un hechizo. Siempre."},
    {"nivel": 69, "titulo": "Hechicero II",   "clase": "Arcano",        "rango": "💠 Diamante",   "tip": "69 niveles. Tu mente es tu herramienta más afilada."},
    {"nivel": 70, "titulo": "Hechicero III",  "clase": "Arcano",        "rango": "💠 Diamante",   "tip": "70 niveles. Lleva un hábito cognitivo al siguiente nivel."},
    {"nivel": 71, "titulo": "Alquimista I",   "clase": "Arcano",        "rango": "💠 Diamante",   "tip": "Transformas cada día ordinario en uno extraordinario. Eso es alquimia."},
    {"nivel": 72, "titulo": "Alquimista II",  "clase": "Arcano",        "rango": "💠 Diamante",   "tip": "Reflexiona: ¿cuál hábito ha cambiado más tu vida?"},
    {"nivel": 73, "titulo": "Alquimista III", "clase": "Arcano",        "rango": "💠 Diamante",   "tip": "A este nivel tus hábitos son tan sólidos que se hacen solos."},
    {"nivel": 74, "titulo": "Oráculo I",      "clase": "Arcano",        "rango": "💠 Diamante",   "tip": "Ves con claridad qué hábitos te llevan más lejos. Úsalos."},
    {"nivel": 75, "titulo": "Oráculo II",     "clase": "Arcano",        "rango": "💠 Diamante",   "tip": "75 niveles. Tres cuartas partes del camino al 100. Épico."},
    {"nivel": 76, "titulo": "Oráculo III",    "clase": "Arcano",        "rango": "💠 Diamante",   "tip": "Escribe una carta a tu yo de nivel 1. Verás cuánto has crecido."},
    {"nivel": 77, "titulo": "Oráculo IV",     "clase": "Arcano",        "rango": "💠 Diamante",   "tip": "Pocos en la historia han llegado aquí. Tú eres uno de ellos."},
    {"nivel": 78, "titulo": "Oráculo V",      "clase": "Arcano",        "rango": "💠 Diamante",   "tip": "Dos niveles para Maestro. El final del camino se acerca."},
    {"nivel": 79, "titulo": "Oráculo VI",     "clase": "Arcano",        "rango": "💠 Diamante",   "tip": "Un nivel más. El rango Maestro te espera. No falles ahora."},
    # ── RANGO 7: MAESTRO (80–89) ───────────────────────────
    {"nivel": 80, "titulo": "Maestro Arcano I",   "clase": "Maestro",   "rango": "🔮 Maestro",   "tip": "¡RANGO MAESTRO! Nivel 80. Eres una leyenda viva del hábito."},
    {"nivel": 81, "titulo": "Maestro Arcano II",  "clase": "Maestro",   "rango": "🔮 Maestro",   "tip": "Tu sistema de hábitos es perfecto. Ahora ayuda a otros a construir el suyo."},
    {"nivel": 82, "titulo": "Maestro Arcano III", "clase": "Maestro",   "rango": "🔮 Maestro",   "tip": "82 niveles. Tu vida es la prueba de que la constancia lo transforma todo."},
    {"nivel": 83, "titulo": "Maestro Supremo I",  "clase": "Maestro",   "rango": "🔮 Maestro",   "tip": "Agrega un hábito espiritual o filosófico que nutra tu propósito."},
    {"nivel": 84, "titulo": "Maestro Supremo II", "clase": "Maestro",   "rango": "🔮 Maestro",   "tip": "La maestría no es perfección, es nunca rendirse. Tú lo sabés."},
    {"nivel": 85, "titulo": "Maestro Supremo III","clase": "Maestro",   "rango": "🔮 Maestro",   "tip": "85 niveles. Escribe un manifiesto personal de tus principios."},
    {"nivel": 86, "titulo": "Archmago I",          "clase": "Maestro",  "rango": "🔮 Maestro",   "tip": "El Archmago domina todos los elementos. Tus 4 stats deben estar altos."},
    {"nivel": 87, "titulo": "Archmago II",         "clase": "Maestro",  "rango": "🔮 Maestro",   "tip": "87 niveles. Tu ejemplo ha cambiado la vida de personas a tu alrededor."},
    {"nivel": 88, "titulo": "Archmago III",        "clase": "Maestro",  "rango": "🔮 Maestro",   "tip": "A dos niveles de la Leyenda Final. Saborea cada día que falta."},
    {"nivel": 89, "titulo": "Archmago IV",         "clase": "Maestro",  "rango": "🔮 Maestro",   "tip": "Un nivel más. El nivel 90 abre el rango Leyenda. Es tu destino."},
    # ── RANGO 8: LEYENDA (90–99) ───────────────────────────
    {"nivel": 90, "titulo": "Leyenda I",      "clase": "Leyenda",       "rango": "👑 Leyenda",    "tip": "¡LEYENDA! Solo tú y un puñado de personas en el mundo están aquí."},
    {"nivel": 91, "titulo": "Leyenda II",     "clase": "Leyenda",       "rango": "👑 Leyenda",    "tip": "Tu historia merece ser contada. Compártela con el mundo."},
    {"nivel": 92, "titulo": "Leyenda III",    "clase": "Leyenda",       "rango": "👑 Leyenda",    "tip": "92 niveles de hábitos. Tu vida es un ejemplo absoluto."},
    {"nivel": 93, "titulo": "Leyenda IV",     "clase": "Leyenda",       "rango": "👑 Leyenda",    "tip": "Cada hábito que cumples a este nivel es pura disciplina pura."},
    {"nivel": 94, "titulo": "Leyenda V",      "clase": "Leyenda",       "rango": "👑 Leyenda",    "tip": "94 niveles. Escribe un libro, un blog, un legado. Lo mereces."},
    {"nivel": 95, "titulo": "Leyenda VI",     "clase": "Leyenda",       "rango": "👑 Leyenda",    "tip": "El 95% completado. Cada nivel que sigue es pura gloria."},
    {"nivel": 96, "titulo": "Leyenda VII",    "clase": "Leyenda",       "rango": "👑 Leyenda",    "tip": "Tu nombre debería estar en un salón de la fama de la disciplina."},
    {"nivel": 97, "titulo": "Leyenda VIII",   "clase": "Leyenda",       "rango": "👑 Leyenda",    "tip": "3 niveles para el máximo. No se llega aquí por accidente."},
    {"nivel": 98, "titulo": "Leyenda IX",     "clase": "Leyenda",       "rango": "👑 Leyenda",    "tip": "Nivel 98. Solo 2 más. Tu constancia no tiene comparación."},
    {"nivel": 99, "titulo": "Leyenda X",      "clase": "Leyenda",       "rango": "👑 Leyenda",    "tip": "El último paso antes de la inmortalidad. No lo desperdicies."},
    # ── RANGO 9: INMORTAL (100) ────────────────────────────
    {"nivel": 100,"titulo": "⚡ INMORTAL",    "clase": "Inmortal",      "rango": "⚡ Inmortal",   "tip": "NIVEL 100. Has alcanzado la cima absoluta. Eres INMORTAL. Tu legado es eterno."},
  ]
  return Evolucion
